/**
 * Addon configuration. Two delivery modes:
 *  - self-hosted single-user: environment variables (.env)
 *  - hosted multi-user: base64url-encoded JSON in the addon URL path
 *    (/{config}/manifest.json — the standard Torrentio-style pattern).
 *
 * `storageKey` is a random opaque id generated by /configure; it scopes the
 * persisted exclusions so instances serving several users don't mix data.
 */
export interface AddonConfig {
  /** Letterboxd username for the RSS delta (requires a public profile). */
  letterboxdUsername?: string;
  /** Free TMDB API key — only needed for RSS mappings Wikidata misses. */
  tmdbApiKey?: string;
  /** Opaque key scoping stored CSV-matched exclusions on this instance. */
  storageKey?: string;
  /** Catalog display name. */
  catalogName?: string;
  /** Manual per-film overrides by imdbId. */
  overrides?: { forceInclude?: string[]; forceExclude?: string[] };
}

export const DEFAULT_STORAGE_KEY = "default";

// runtime-agnostic base64url (Buffer is not available on Workers)
function b64urlEncode(s: string): string {
  const bytes = new TextEncoder().encode(s);
  let bin = "";
  for (const b of bytes) bin += String.fromCharCode(b);
  return btoa(bin).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

function b64urlDecode(s: string): string {
  const bin = atob(s.replace(/-/g, "+").replace(/_/g, "/"));
  const bytes = Uint8Array.from(bin, (c) => c.charCodeAt(0));
  return new TextDecoder().decode(bytes);
}

export function encodeConfig(cfg: AddonConfig): string {
  return b64urlEncode(JSON.stringify(cfg));
}

const IMDB_ID = /^tt\d{4,10}$/;
const STRING_FIELDS = ["letterboxdUsername", "tmdbApiKey", "storageKey", "catalogName"] as const;

// String fields land in KV keys (`watched:rss:{username}`, `watched:csv:{key}`)
// whose limit is 512 bytes — an unbounded value could crash a request.
const STRING_FIELD_MAX: Record<(typeof STRING_FIELDS)[number], number> = {
  letterboxdUsername: 100,
  tmdbApiKey: 300, // TMDB v4 read tokens are ~200-char JWTs
  storageKey: 100,
  catalogName: 100,
};

/**
 * Decodes and validates a URL config. Unknown keys are dropped; known keys
 * with the wrong type reject the whole config (a malformed cfg must fall back
 * to the env config, not silently produce a half-broken addon).
 */
export function decodeConfig(raw: string): AddonConfig | null {
  try {
    const obj = JSON.parse(b64urlDecode(raw)) as unknown;
    if (typeof obj !== "object" || obj === null || Array.isArray(obj)) return null;
    const o = obj as Record<string, unknown>;
    const cfg: AddonConfig = {};
    for (const k of STRING_FIELDS) {
      const v = o[k];
      if (v === undefined) continue;
      if (typeof v !== "string" || v.length === 0 || v.length > STRING_FIELD_MAX[k]) return null;
      cfg[k] = v;
    }
    if (o.overrides !== undefined) {
      const ov = o.overrides;
      if (typeof ov !== "object" || ov === null || Array.isArray(ov)) return null;
      const overrides: NonNullable<AddonConfig["overrides"]> = {};
      for (const k of ["forceInclude", "forceExclude"] as const) {
        const v = (ov as Record<string, unknown>)[k];
        if (v === undefined) continue;
        if (!Array.isArray(v) || !v.every((id) => typeof id === "string" && IMDB_ID.test(id))) return null;
        overrides[k] = v;
      }
      cfg.overrides = overrides;
    }
    return cfg;
  } catch {
    return null;
  }
}

export function configFromEnv(env: Record<string, string | undefined>): AddonConfig {
  const cfg: AddonConfig = {};
  if (env.LETTERBOXD_USERNAME) cfg.letterboxdUsername = env.LETTERBOXD_USERNAME;
  if (env.TMDB_API_KEY) cfg.tmdbApiKey = env.TMDB_API_KEY;
  if (env.CATALOG_NAME) cfg.catalogName = env.CATALOG_NAME;
  return cfg;
}
